language: php

php:
  - 5.5
  - 5.6

env:
  - NETTE=default
  - NETTE=nette-2.1

install:
  - php ./tests/prepare-composer.php
  - composer self-update || echo "failed :("
  - time composer install --no-interaction --prefer-source --dev

before_script:
  - ./vendor/bin/tester -c ./tests/php.ini-unix --info
  - time ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - ./vendor/bin/tester -s -j 32 -c ./tests/php.ini-unix ./tests/

after_failure:
  - 'for i in $(find ./log -name \*.log); do echo "--- $i"; cat $i; echo; echo; done'
  - 'for i in $(find ./tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done'
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

#cache:
#  directories:
#    - vendor

notifications:
  hipchat:
    rooms:
      - d3defec158bc15ad4d67d3fb712218@723387
    template:
      - '<a href="%{build_url}">build#%{build_number}</a> on %{branch} by %{author}: %{message}<br> - %{commit_message} (<a href="%{compare_url}">%{commit}</a>)'
    format: html
  email: false
